WIP —  WTF arf
Danmit I've been working on something that don't build on PROD

 WebpackError: [React Intl] Could not find required `intl` object. <IntlProvide  r> needs to exist in the component ancestry.